package com.xhp.crowdfunding.dao;

import com.xhp.crowdfunding.entity.Projectclassification;

public interface ProjectclassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int insert(Projectclassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int insertSelective(Projectclassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    Projectclassification selectByPrimaryKey(String pcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Projectclassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Projectclassification record);
}