package com.xhp.crowdfunding.entity;

import java.util.Date;

public class Approval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Aid
     *
     * @mbg.generated
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Astate
     *
     * @mbg.generated
     */
    private String astate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Adate
     *
     * @mbg.generated
     */
    private Date adate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.Aid
     *
     * @return the value of approval.Aid
     *
     * @mbg.generated
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.Aid
     *
     * @param aid the value for approval.Aid
     *
     * @mbg.generated
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.Astate
     *
     * @return the value of approval.Astate
     *
     * @mbg.generated
     */
    public String getAstate() {
        return astate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.Astate
     *
     * @param astate the value for approval.Astate
     *
     * @mbg.generated
     */
    public void setAstate(String astate) {
        this.astate = astate == null ? null : astate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.Pid
     *
     * @return the value of approval.Pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.Pid
     *
     * @param pid the value for approval.Pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.Adate
     *
     * @return the value of approval.Adate
     *
     * @mbg.generated
     */
    public Date getAdate() {
        return adate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.Adate
     *
     * @param adate the value for approval.Adate
     *
     * @mbg.generated
     */
    public void setAdate(Date adate) {
        this.adate = adate;
    }
}