package com.xhp.crowdfunding.entity;

public class Homecarousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homecarousel.HCid
     *
     * @mbg.generated
     */
    private String hcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homecarousel.HCimage
     *
     * @mbg.generated
     */
    private String hcimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homecarousel.HCid
     *
     * @return the value of homecarousel.HCid
     *
     * @mbg.generated
     */
    public String getHcid() {
        return hcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homecarousel.HCid
     *
     * @param hcid the value for homecarousel.HCid
     *
     * @mbg.generated
     */
    public void setHcid(String hcid) {
        this.hcid = hcid == null ? null : hcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homecarousel.HCimage
     *
     * @return the value of homecarousel.HCimage
     *
     * @mbg.generated
     */
    public String getHcimage() {
        return hcimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homecarousel.HCimage
     *
     * @param hcimage the value for homecarousel.HCimage
     *
     * @mbg.generated
     */
    public void setHcimage(String hcimage) {
        this.hcimage = hcimage == null ? null : hcimage.trim();
    }
}