package com.xhp.crowdfunding.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mpassword
     *
     * @mbg.generated
     */
    private String mpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mname
     *
     * @mbg.generated
     */
    private String mname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mid
     *
     * @return the value of manager.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mid
     *
     * @param mid the value for manager.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mpassword
     *
     * @return the value of manager.mpassword
     *
     * @mbg.generated
     */
    public String getMpassword() {
        return mpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mpassword
     *
     * @param mpassword the value for manager.mpassword
     *
     * @mbg.generated
     */
    public void setMpassword(String mpassword) {
        this.mpassword = mpassword == null ? null : mpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mname
     *
     * @return the value of manager.mname
     *
     * @mbg.generated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mname
     *
     * @param mname the value for manager.mname
     *
     * @mbg.generated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }
}