package com.xhp.crowdfunding.entity;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Oid
     *
     * @mbg.generated
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Ostate
     *
     * @mbg.generated
     */
    private String ostate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Omoney
     *
     * @mbg.generated
     */
    private Integer omoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Oid
     *
     * @return the value of order.Oid
     *
     * @mbg.generated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Oid
     *
     * @param oid the value for order.Oid
     *
     * @mbg.generated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Pid
     *
     * @return the value of order.Pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Pid
     *
     * @param pid the value for order.Pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Uid
     *
     * @return the value of order.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Uid
     *
     * @param uid the value for order.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Ostate
     *
     * @return the value of order.Ostate
     *
     * @mbg.generated
     */
    public String getOstate() {
        return ostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Ostate
     *
     * @param ostate the value for order.Ostate
     *
     * @mbg.generated
     */
    public void setOstate(String ostate) {
        this.ostate = ostate == null ? null : ostate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Omoney
     *
     * @return the value of order.Omoney
     *
     * @mbg.generated
     */
    public Integer getOmoney() {
        return omoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Omoney
     *
     * @param omoney the value for order.Omoney
     *
     * @mbg.generated
     */
    public void setOmoney(Integer omoney) {
        this.omoney = omoney;
    }
}