package com.xhp.crowdfunding.entity;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.paccountName
     *
     * @mbg.generated
     */
    private String paccountname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pidentify
     *
     * @mbg.generated
     */
    private String pidentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.paccountTel
     *
     * @mbg.generated
     */
    private String paccounttel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ploc
     *
     * @mbg.generated
     */
    private String ploc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pimage
     *
     * @mbg.generated
     */
    private String pimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pcontent
     *
     * @mbg.generated
     */
    private String pcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pdate
     *
     * @mbg.generated
     */
    private String pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ptargetMoney
     *
     * @mbg.generated
     */
    private Integer ptargetmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.praiseDays
     *
     * @mbg.generated
     */
    private Integer praisedays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ppresentMoney
     *
     * @mbg.generated
     */
    private Integer ppresentmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ptags
     *
     * @mbg.generated
     */
    private String ptags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pdescripTitle
     *
     * @mbg.generated
     */
    private String pdescriptitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pdescripCont
     *
     * @mbg.generated
     */
    private String pdescripcont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.prepayType
     *
     * @mbg.generated
     */
    private String prepaytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.prepayTitle
     *
     * @mbg.generated
     */
    private String prepaytitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.prepayCont
     *
     * @mbg.generated
     */
    private String prepaycont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pcid
     *
     * @mbg.generated
     */
    private Integer pcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pid
     *
     * @return the value of project.pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pid
     *
     * @param pid the value for project.pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.paccountName
     *
     * @return the value of project.paccountName
     *
     * @mbg.generated
     */
    public String getPaccountname() {
        return paccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.paccountName
     *
     * @param paccountname the value for project.paccountName
     *
     * @mbg.generated
     */
    public void setPaccountname(String paccountname) {
        this.paccountname = paccountname == null ? null : paccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pidentify
     *
     * @return the value of project.pidentify
     *
     * @mbg.generated
     */
    public String getPidentify() {
        return pidentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pidentify
     *
     * @param pidentify the value for project.pidentify
     *
     * @mbg.generated
     */
    public void setPidentify(String pidentify) {
        this.pidentify = pidentify == null ? null : pidentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.paccountTel
     *
     * @return the value of project.paccountTel
     *
     * @mbg.generated
     */
    public String getPaccounttel() {
        return paccounttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.paccountTel
     *
     * @param paccounttel the value for project.paccountTel
     *
     * @mbg.generated
     */
    public void setPaccounttel(String paccounttel) {
        this.paccounttel = paccounttel == null ? null : paccounttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ploc
     *
     * @return the value of project.ploc
     *
     * @mbg.generated
     */
    public String getPloc() {
        return ploc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ploc
     *
     * @param ploc the value for project.ploc
     *
     * @mbg.generated
     */
    public void setPloc(String ploc) {
        this.ploc = ploc == null ? null : ploc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pimage
     *
     * @return the value of project.pimage
     *
     * @mbg.generated
     */
    public String getPimage() {
        return pimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pimage
     *
     * @param pimage the value for project.pimage
     *
     * @mbg.generated
     */
    public void setPimage(String pimage) {
        this.pimage = pimage == null ? null : pimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pname
     *
     * @return the value of project.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pname
     *
     * @param pname the value for project.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pcontent
     *
     * @return the value of project.pcontent
     *
     * @mbg.generated
     */
    public String getPcontent() {
        return pcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pcontent
     *
     * @param pcontent the value for project.pcontent
     *
     * @mbg.generated
     */
    public void setPcontent(String pcontent) {
        this.pcontent = pcontent == null ? null : pcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pdate
     *
     * @return the value of project.pdate
     *
     * @mbg.generated
     */
    public String getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pdate
     *
     * @param pdate the value for project.pdate
     *
     * @mbg.generated
     */
    public void setPdate(String pdate) {
        this.pdate = pdate == null ? null : pdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ptargetMoney
     *
     * @return the value of project.ptargetMoney
     *
     * @mbg.generated
     */
    public Integer getPtargetmoney() {
        return ptargetmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ptargetMoney
     *
     * @param ptargetmoney the value for project.ptargetMoney
     *
     * @mbg.generated
     */
    public void setPtargetmoney(Integer ptargetmoney) {
        this.ptargetmoney = ptargetmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.praiseDays
     *
     * @return the value of project.praiseDays
     *
     * @mbg.generated
     */
    public Integer getPraisedays() {
        return praisedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.praiseDays
     *
     * @param praisedays the value for project.praiseDays
     *
     * @mbg.generated
     */
    public void setPraisedays(Integer praisedays) {
        this.praisedays = praisedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ppresentMoney
     *
     * @return the value of project.ppresentMoney
     *
     * @mbg.generated
     */
    public Integer getPpresentmoney() {
        return ppresentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ppresentMoney
     *
     * @param ppresentmoney the value for project.ppresentMoney
     *
     * @mbg.generated
     */
    public void setPpresentmoney(Integer ppresentmoney) {
        this.ppresentmoney = ppresentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ptags
     *
     * @return the value of project.ptags
     *
     * @mbg.generated
     */
    public String getPtags() {
        return ptags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ptags
     *
     * @param ptags the value for project.ptags
     *
     * @mbg.generated
     */
    public void setPtags(String ptags) {
        this.ptags = ptags == null ? null : ptags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pdescripTitle
     *
     * @return the value of project.pdescripTitle
     *
     * @mbg.generated
     */
    public String getPdescriptitle() {
        return pdescriptitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pdescripTitle
     *
     * @param pdescriptitle the value for project.pdescripTitle
     *
     * @mbg.generated
     */
    public void setPdescriptitle(String pdescriptitle) {
        this.pdescriptitle = pdescriptitle == null ? null : pdescriptitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pdescripCont
     *
     * @return the value of project.pdescripCont
     *
     * @mbg.generated
     */
    public String getPdescripcont() {
        return pdescripcont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pdescripCont
     *
     * @param pdescripcont the value for project.pdescripCont
     *
     * @mbg.generated
     */
    public void setPdescripcont(String pdescripcont) {
        this.pdescripcont = pdescripcont == null ? null : pdescripcont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.prepayType
     *
     * @return the value of project.prepayType
     *
     * @mbg.generated
     */
    public String getPrepaytype() {
        return prepaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.prepayType
     *
     * @param prepaytype the value for project.prepayType
     *
     * @mbg.generated
     */
    public void setPrepaytype(String prepaytype) {
        this.prepaytype = prepaytype == null ? null : prepaytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.prepayTitle
     *
     * @return the value of project.prepayTitle
     *
     * @mbg.generated
     */
    public String getPrepaytitle() {
        return prepaytitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.prepayTitle
     *
     * @param prepaytitle the value for project.prepayTitle
     *
     * @mbg.generated
     */
    public void setPrepaytitle(String prepaytitle) {
        this.prepaytitle = prepaytitle == null ? null : prepaytitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.prepayCont
     *
     * @return the value of project.prepayCont
     *
     * @mbg.generated
     */
    public String getPrepaycont() {
        return prepaycont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.prepayCont
     *
     * @param prepaycont the value for project.prepayCont
     *
     * @mbg.generated
     */
    public void setPrepaycont(String prepaycont) {
        this.prepaycont = prepaycont == null ? null : prepaycont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pcid
     *
     * @return the value of project.pcid
     *
     * @mbg.generated
     */
    public Integer getPcid() {
        return pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pcid
     *
     * @param pcid the value for project.pcid
     *
     * @mbg.generated
     */
    public void setPcid(Integer pcid) {
        this.pcid = pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.uid
     *
     * @return the value of project.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.uid
     *
     * @param uid the value for project.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}