package com.xhp.crowdfunding.entity;

public class Sponsor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor.Sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor.Sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor.Smoney
     *
     * @mbg.generated
     */
    private Integer smoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor.Sid
     *
     * @return the value of sponsor.Sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor.Sid
     *
     * @param sid the value for sponsor.Sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor.Sname
     *
     * @return the value of sponsor.Sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor.Sname
     *
     * @param sname the value for sponsor.Sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor.Smoney
     *
     * @return the value of sponsor.Smoney
     *
     * @mbg.generated
     */
    public Integer getSmoney() {
        return smoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor.Smoney
     *
     * @param smoney the value for sponsor.Smoney
     *
     * @mbg.generated
     */
    public void setSmoney(Integer smoney) {
        this.smoney = smoney;
    }
}