package com.xhp.crowdfunding.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.unickname
     *
     * @mbg.generated
     */
    private String unickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upassword
     *
     * @mbg.generated
     */
    private String upassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usex
     *
     * @mbg.generated
     */
    private String usex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uidNumber
     *
     * @mbg.generated
     */
    private String uidnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uphone
     *
     * @mbg.generated
     */
    private String uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uimage
     *
     * @mbg.generated
     */
    private String uimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbg.generated
     */
    private String uemail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.unickname
     *
     * @return the value of user.unickname
     *
     * @mbg.generated
     */
    public String getUnickname() {
        return unickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.unickname
     *
     * @param unickname the value for user.unickname
     *
     * @mbg.generated
     */
    public void setUnickname(String unickname) {
        this.unickname = unickname == null ? null : unickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upassword
     *
     * @return the value of user.upassword
     *
     * @mbg.generated
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upassword
     *
     * @param upassword the value for user.upassword
     *
     * @mbg.generated
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usex
     *
     * @return the value of user.usex
     *
     * @mbg.generated
     */
    public String getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usex
     *
     * @param usex the value for user.usex
     *
     * @mbg.generated
     */
    public void setUsex(String usex) {
        this.usex = usex == null ? null : usex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uidNumber
     *
     * @return the value of user.uidNumber
     *
     * @mbg.generated
     */
    public String getUidnumber() {
        return uidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uidNumber
     *
     * @param uidnumber the value for user.uidNumber
     *
     * @mbg.generated
     */
    public void setUidnumber(String uidnumber) {
        this.uidnumber = uidnumber == null ? null : uidnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uphone
     *
     * @return the value of user.uphone
     *
     * @mbg.generated
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uphone
     *
     * @param uphone the value for user.uphone
     *
     * @mbg.generated
     */
    public void setUphone(String uphone) {
        this.uphone = uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uimage
     *
     * @return the value of user.uimage
     *
     * @mbg.generated
     */
    public String getUimage() {
        return uimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uimage
     *
     * @param uimage the value for user.uimage
     *
     * @mbg.generated
     */
    public void setUimage(String uimage) {
        this.uimage = uimage == null ? null : uimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uemail
     *
     * @return the value of user.uemail
     *
     * @mbg.generated
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uemail
     *
     * @param uemail the value for user.uemail
     *
     * @mbg.generated
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }
}